
package Practicals.Practical3.CMatrix;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MatrixServiceService", targetNamespace = "http://Practical3.Practicals/", wsdlLocation = "http://localhost:8883/matrix?wsdl")
public class MatrixServiceService
    extends Service
{

    private final static URL MATRIXSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MATRIXSERVICESERVICE_EXCEPTION;
    private final static QName MATRIXSERVICESERVICE_QNAME = new QName("http://Practical3.Practicals/", "MatrixServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8883/matrix?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATRIXSERVICESERVICE_WSDL_LOCATION = url;
        MATRIXSERVICESERVICE_EXCEPTION = e;
    }

    public MatrixServiceService() {
        super(__getWsdlLocation(), MATRIXSERVICESERVICE_QNAME);
    }

    public MatrixServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATRIXSERVICESERVICE_QNAME, features);
    }

    public MatrixServiceService(URL wsdlLocation) {
        super(wsdlLocation, MATRIXSERVICESERVICE_QNAME);
    }

    public MatrixServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATRIXSERVICESERVICE_QNAME, features);
    }

    public MatrixServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MatrixServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MatrixInterface
     */
    @WebEndpoint(name = "MatrixServicePort")
    public MatrixInterface getMatrixServicePort() {
        return super.getPort(new QName("http://Practical3.Practicals/", "MatrixServicePort"), MatrixInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MatrixInterface
     */
    @WebEndpoint(name = "MatrixServicePort")
    public MatrixInterface getMatrixServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Practical3.Practicals/", "MatrixServicePort"), MatrixInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATRIXSERVICESERVICE_EXCEPTION!= null) {
            throw MATRIXSERVICESERVICE_EXCEPTION;
        }
        return MATRIXSERVICESERVICE_WSDL_LOCATION;
    }

}
